import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Sidebar from '@/components/sidebar';
import { Box, createTheme, Grid, ThemeProvider } from '@mui/material';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Dashboard CIAC - SDPD',
	description: 'Generated by create next app',
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<Box
					sx={{
						display: 'flex',
						flexDirection: 'row',
						margin: 'auto',
					}}
				>
					<Sidebar />

					{/* </Container> */}
					<Grid item xs={12} sx={{ margin: 'auto', justifySelf: 'center' }}>
						{children}
					</Grid>
				</Box>
			</body>
		</html>
	);
}
