import Sidebar from '@/components/sidebar';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Dashboard CIAC - SDPD',
	description: 'Generated by create next app',
};
export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<div className="flex flex-row m-auto">
					<Sidebar />

					<div className="flex flex-col justify-center m-auto">{children}</div>
				</div>
			</body>
		</html>
	);
}
